apiVersion: v2.xp-layers.crossplane.io/v1alpha1
kind: Network
metadata:
 name: network-iteration
 namespace: xp-v2
spec:
  id: "iteration"
  count: 2
  includeGateway: true
  providerConfigName: default
  region: eu-central-1
  crossplane:
    compositionSelector:
      matchLabels:
       layer: functions