apiVersion: ec2.aws.upbound.io/v1beta1
kind: VPC
metadata:
  name: vpc-1
  labels:
    xp-layers.crossplane.io/vpc-id: vpc-1
spec:
  forProvider:
    region: us-west-2
    cidrBlock: 192.168.0.0/16
    enableDnsSupport: true
    enableDnsHostnames: true
  providerConfigRef:
    name: default
