apiVersion: xp-layers.crossplane.io/v1alpha1
kind: Network
metadata:
 name: network-conditional
 namespace: default
spec:
  id: "conditional"
  count: 1
  includeGateway: false
  providerConfigName: default
  region: eu-central-1
  compositionSelector:
    matchLabels:
      layer: functions