apiVersion: pkg.crossplane.io/v1beta1
kind: Function
metadata:
  name: demo-xfn-network
spec:
  package: xpkg.upbound.io/jaredorg/demo-xfn-network:v0.0.1
---
apiVersion: pkg.crossplane.io/v1beta1
kind: Function
metadata:
  name: function-auto-ready
spec:
  package: xpkg.upbound.io/crossplane-contrib/function-auto-ready:v0.2.1